#!/usr/bin/bash
~/.config/waybar/scripts/tools/dynamic &
while true
do
    # echo ""
    out=$(cat ~/.config/waybar/store/dynamic_out.txt)
    echo "$out"  | jq --unbuffered --compact-output
    sleep 0.5
done