-- Plugins
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.whichkey")
require("plugins.colorizer")
require("plugins.toggleterm")
require("plugins.illuminate")
require("plugins.indent-blankline")
require("plugins.noice")

-- lsp
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
